// This file was generated by flutterfire configure.
// Ignored files: lib/firebase_options.dart

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfQ9h_OMTGrkCEU2WGhSMEP9DWzdIDYw',
    appId: '1:363607195624:web:c4eb1d6292bc3536402e5d',
    messagingSenderId: '363607195624',
    projectId: 'wifihaat-135c3',
    authDomain: 'wifihaat-135c3.firebaseapp.com',
    storageBucket: 'wifihaat-135c3.firebasestorage.app',
    measurementId: 'G-CFDVW5QW6M',
  );
}
